// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package ping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	RequestId            string               `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SourceName           string               `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SentOn               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=sent_on,json=sentOn,proto3" json:"sent_on,omitempty"`
	Targets              []string             `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Request) GetSourceName() string {
	if m != nil {
		return m.SourceName
	}
	return ""
}

func (m *Request) GetSentOn() *timestamp.Timestamp {
	if m != nil {
		return m.SentOn
	}
	return nil
}

func (m *Request) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Response struct {
	RequestId            string               `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target               string               `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ProcessedOn          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=processed_on,json=processedOn,proto3" json:"processed_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Response) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Response) GetProcessedOn() *timestamp.Timestamp {
	if m != nil {
		return m.ProcessedOn
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "ping.Request")
	proto.RegisterType((*Response)(nil), "ping.Response")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4e, 0xb4, 0x30,
	0x14, 0xc5, 0x3f, 0xbe, 0x21, 0x20, 0x17, 0xc7, 0x45, 0x17, 0x86, 0x90, 0x98, 0x21, 0x6c, 0x64,
	0xd5, 0x49, 0x66, 0x12, 0x77, 0x3e, 0x80, 0x1b, 0xc7, 0xa0, 0x7b, 0xc2, 0xc0, 0xb5, 0x21, 0xb1,
	0x7f, 0xec, 0x2d, 0xae, 0x7d, 0x0c, 0x1f, 0xd7, 0x40, 0xc1, 0xad, 0xee, 0x7a, 0x4e, 0x4f, 0x7b,
	0x7e, 0x39, 0xb0, 0x95, 0x48, 0xd4, 0x0a, 0xe4, 0xc6, 0x6a, 0xa7, 0x59, 0x68, 0x06, 0x25, 0xf2,
	0x9d, 0xd0, 0x5a, 0xbc, 0xe1, 0x7e, 0xf6, 0xce, 0xe3, 0xeb, 0xde, 0x0d, 0x12, 0xc9, 0xb5, 0xd2,
	0xf8, 0x58, 0xf9, 0x15, 0x40, 0x5c, 0xe3, 0xfb, 0x88, 0xe4, 0xd8, 0x0d, 0x80, 0xf5, 0xc7, 0x66,
	0xe8, 0xb3, 0xa0, 0x08, 0xaa, 0xa4, 0x4e, 0x16, 0xe7, 0xa1, 0x67, 0x3b, 0x48, 0x49, 0x8f, 0xb6,
	0xc3, 0x46, 0xb5, 0x12, 0xb3, 0xff, 0xf3, 0x3d, 0x78, 0xeb, 0xb1, 0x95, 0xc8, 0x8e, 0x10, 0x13,
	0x2a, 0xd7, 0x68, 0x95, 0x6d, 0x8a, 0xa0, 0x4a, 0x0f, 0x39, 0xf7, 0xf5, 0x7c, 0xad, 0xe7, 0x2f,
	0x6b, 0x7d, 0x1d, 0x4d, 0xd1, 0x93, 0x62, 0x19, 0xc4, 0xae, 0xb5, 0x02, 0x1d, 0x65, 0x61, 0xb1,
	0xa9, 0x92, 0x7a, 0x95, 0xe5, 0x67, 0x00, 0x17, 0x35, 0x92, 0xd1, 0x8a, 0xf0, 0x37, 0xb6, 0x6b,
	0x88, 0xfc, 0xb3, 0x05, 0x6b, 0x51, 0xec, 0x1e, 0x2e, 0x8d, 0xd5, 0x1d, 0x12, 0x61, 0xff, 0x37,
	0xae, 0xf4, 0x27, 0x7f, 0x52, 0x87, 0x3b, 0x48, 0x9f, 0x06, 0x25, 0x9e, 0xd1, 0x7e, 0x0c, 0x1d,
	0xb2, 0x5b, 0x08, 0x27, 0xc9, 0xb6, 0x7c, 0x1a, 0x97, 0x2f, 0xbb, 0xe5, 0x57, 0xab, 0xf4, 0xac,
	0xe5, 0xbf, 0x73, 0x34, 0x7f, 0x7c, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x49, 0xcd, 0xa3,
	0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingServiceClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPingServiceClient(cc *grpc.ClientConn) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ping.PingService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServiceServer is the server API for PingService service.
type PingServiceServer interface {
	Ping(context.Context, *Request) (*Response, error)
}

func RegisterPingServiceServer(s *grpc.Server, srv PingServiceServer) {
	s.RegisterService(&_PingService_serviceDesc, srv)
}

func _PingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ping.PingService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServiceServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ping.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
