// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package echo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BroadcastMessage struct {
	Self                 *Node    `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Targets              []*Node  `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastMessage) Reset()         { *m = BroadcastMessage{} }
func (m *BroadcastMessage) String() string { return proto.CompactTextString(m) }
func (*BroadcastMessage) ProtoMessage()    {}
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BroadcastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastMessage.Unmarshal(m, b)
}
func (m *BroadcastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastMessage.Marshal(b, m, deterministic)
}
func (m *BroadcastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastMessage.Merge(m, src)
}
func (m *BroadcastMessage) XXX_Size() int {
	return xxx_messageInfo_BroadcastMessage.Size(m)
}
func (m *BroadcastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastMessage proto.InternalMessageInfo

func (m *BroadcastMessage) GetSelf() *Node {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *BroadcastMessage) GetTargets() []*Node {
	if m != nil {
		return m.Targets
	}
	return nil
}

type BroadcastResult struct {
	Source               *Node    `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target               *Node    `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Duration             int64    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastResult) Reset()         { *m = BroadcastResult{} }
func (m *BroadcastResult) String() string { return proto.CompactTextString(m) }
func (*BroadcastResult) ProtoMessage()    {}
func (*BroadcastResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *BroadcastResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResult.Unmarshal(m, b)
}
func (m *BroadcastResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResult.Marshal(b, m, deterministic)
}
func (m *BroadcastResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResult.Merge(m, src)
}
func (m *BroadcastResult) XXX_Size() int {
	return xxx_messageInfo_BroadcastResult.Size(m)
}
func (m *BroadcastResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResult.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResult proto.InternalMessageInfo

func (m *BroadcastResult) GetSource() *Node {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *BroadcastResult) GetTarget() *Node {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *BroadcastResult) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *BroadcastResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BroadcastResults struct {
	Results              []*BroadcastResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BroadcastResults) Reset()         { *m = BroadcastResults{} }
func (m *BroadcastResults) String() string { return proto.CompactTextString(m) }
func (*BroadcastResults) ProtoMessage()    {}
func (*BroadcastResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *BroadcastResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastResults.Unmarshal(m, b)
}
func (m *BroadcastResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastResults.Marshal(b, m, deterministic)
}
func (m *BroadcastResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastResults.Merge(m, src)
}
func (m *BroadcastResults) XXX_Size() int {
	return xxx_messageInfo_BroadcastResults.Size(m)
}
func (m *BroadcastResults) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastResults.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastResults proto.InternalMessageInfo

func (m *BroadcastResults) GetResults() []*BroadcastResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type NodeResult struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeResult) Reset()         { *m = NodeResult{} }
func (m *NodeResult) String() string { return proto.CompactTextString(m) }
func (*NodeResult) ProtoMessage()    {}
func (*NodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *NodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeResult.Unmarshal(m, b)
}
func (m *NodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeResult.Marshal(b, m, deterministic)
}
func (m *NodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResult.Merge(m, src)
}
func (m *NodeResult) XXX_Size() int {
	return xxx_messageInfo_NodeResult.Size(m)
}
func (m *NodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResult proto.InternalMessageInfo

func (m *NodeResult) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Node struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Node) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Node) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type EchoMessage struct {
	From                 string               `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Sent                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=sent,proto3" json:"sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EchoMessage) Reset()         { *m = EchoMessage{} }
func (m *EchoMessage) String() string { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()    {}
func (*EchoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *EchoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoMessage.Unmarshal(m, b)
}
func (m *EchoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoMessage.Marshal(b, m, deterministic)
}
func (m *EchoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoMessage.Merge(m, src)
}
func (m *EchoMessage) XXX_Size() int {
	return xxx_messageInfo_EchoMessage.Size(m)
}
func (m *EchoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EchoMessage proto.InternalMessageInfo

func (m *EchoMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EchoMessage) GetSent() *timestamp.Timestamp {
	if m != nil {
		return m.Sent
	}
	return nil
}

func init() {
	proto.RegisterType((*BroadcastMessage)(nil), "echo.BroadcastMessage")
	proto.RegisterType((*BroadcastResult)(nil), "echo.BroadcastResult")
	proto.RegisterType((*BroadcastResults)(nil), "echo.BroadcastResults")
	proto.RegisterType((*NodeResult)(nil), "echo.NodeResult")
	proto.RegisterType((*Node)(nil), "echo.Node")
	proto.RegisterType((*EchoMessage)(nil), "echo.EchoMessage")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x3d, 0x6f, 0xea, 0x30,
	0x14, 0x25, 0x24, 0xc0, 0xcb, 0x45, 0x4f, 0x8f, 0x77, 0x45, 0x51, 0x94, 0xa1, 0x8d, 0xac, 0x0e,
	0x4c, 0x46, 0xa2, 0x73, 0x97, 0x7e, 0x8c, 0xad, 0x54, 0xb7, 0x43, 0xd7, 0x10, 0x4c, 0x88, 0x04,
	0x18, 0x5d, 0x3b, 0x9d, 0xfa, 0x0f, 0xfa, 0xa7, 0x2b, 0xdb, 0x09, 0x42, 0xc0, 0x76, 0x3f, 0x8e,
	0xce, 0x3d, 0xc7, 0xc7, 0xf0, 0x57, 0x4b, 0xfa, 0xaa, 0x0a, 0xc9, 0xf7, 0xa4, 0x8c, 0xc2, 0x48,
	0x16, 0x6b, 0x95, 0xde, 0x94, 0x4a, 0x95, 0x1b, 0x39, 0x73, 0xb3, 0x45, 0xbd, 0x9a, 0x99, 0x6a,
	0x2b, 0xb5, 0xc9, 0xb7, 0x7b, 0x0f, 0x63, 0x9f, 0x30, 0x7a, 0x20, 0x95, 0x2f, 0x8b, 0x5c, 0x9b,
	0x17, 0xa9, 0x75, 0x5e, 0x4a, 0xbc, 0x86, 0x48, 0xcb, 0xcd, 0x2a, 0x09, 0xb2, 0x60, 0x3a, 0x9c,
	0x03, 0xb7, 0x4c, 0xfc, 0x55, 0x2d, 0xa5, 0x70, 0x73, 0xbc, 0x85, 0x81, 0xc9, 0xa9, 0x94, 0x46,
	0x27, 0xdd, 0x2c, 0x3c, 0x81, 0xb4, 0x2b, 0xf6, 0x13, 0xc0, 0xbf, 0x03, 0xb5, 0x90, 0xba, 0xde,
	0x18, 0x64, 0xd0, 0xd7, 0xaa, 0xa6, 0x42, 0x5e, 0xe0, 0x6e, 0x36, 0x16, 0xe3, 0x29, 0x92, 0xee,
	0x39, 0xc6, 0x6f, 0x30, 0x85, 0x3f, 0xcb, 0x9a, 0x72, 0x53, 0xa9, 0x5d, 0x12, 0x66, 0xc1, 0x34,
	0x14, 0x87, 0x1e, 0xc7, 0xd0, 0x93, 0x44, 0x8a, 0x92, 0x28, 0x0b, 0xa6, 0xb1, 0xf0, 0x0d, 0x7b,
	0x3c, 0xf2, 0xe9, 0xc5, 0x68, 0x9c, 0xc1, 0x80, 0x7c, 0x99, 0x04, 0xce, 0xc7, 0x95, 0x3f, 0x75,
	0x02, 0x14, 0x2d, 0x8a, 0x31, 0x00, 0x27, 0xc3, 0x9b, 0x19, 0x43, 0xaf, 0x50, 0xf5, 0xce, 0x38,
	0x2f, 0x3d, 0xe1, 0x1b, 0xf6, 0x04, 0x91, 0xc5, 0xe0, 0x04, 0xfa, 0x24, 0x4b, 0x2b, 0x30, 0x70,
	0x3a, 0x9a, 0x0e, 0x47, 0x10, 0xd6, 0x54, 0x39, 0x6f, 0xb1, 0xb0, 0x25, 0x22, 0x44, 0x7b, 0x45,
	0xc6, 0x19, 0x89, 0x85, 0xab, 0xd9, 0x1b, 0x0c, 0x9f, 0x8b, 0xb5, 0x6a, 0x13, 0x41, 0x88, 0x56,
	0xa4, 0xb6, 0x0d, 0x95, 0xab, 0x91, 0xdb, 0x94, 0x76, 0xed, 0x2b, 0xa5, 0xdc, 0x27, 0xcd, 0xdb,
	0xa4, 0xf9, 0x47, 0x9b, 0xb4, 0x70, 0xb8, 0xf9, 0xb7, 0xa7, 0x7c, 0xf7, 0xbf, 0x04, 0xef, 0x21,
	0x3e, 0xf8, 0xc4, 0xc9, 0x89, 0xf1, 0xe6, 0x6e, 0x3a, 0xb9, 0xf8, 0x20, 0x9a, 0x75, 0xec, 0x75,
	0xcb, 0x86, 0xff, 0x3d, 0xe2, 0x48, 0x6c, 0x7a, 0x3e, 0x62, 0x9d, 0x45, 0xdf, 0xe9, 0xba, 0xfb,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xde, 0x25, 0x7a, 0xa6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoServiceClient is the client API for EchoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoServiceClient interface {
	Broadcast(ctx context.Context, in *BroadcastMessage, opts ...grpc.CallOption) (*BroadcastResults, error)
	Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Broadcast(ctx context.Context, in *BroadcastMessage, opts ...grpc.CallOption) (*BroadcastResults, error) {
	out := new(BroadcastResults)
	err := c.cc.Invoke(ctx, "/echo.EchoService/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error) {
	out := new(EchoMessage)
	err := c.cc.Invoke(ctx, "/echo.EchoService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServiceServer is the server API for EchoService service.
type EchoServiceServer interface {
	Broadcast(context.Context, *BroadcastMessage) (*BroadcastResults, error)
	Echo(context.Context, *EchoMessage) (*EchoMessage, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Broadcast(ctx, req.(*BroadcastMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _EchoService_Broadcast_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _EchoService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
